// 本文件提供可复用的 status 展示组件，供各功能页面组合使用并保持交互表现一致。
// statusText 是所有页面共享的后端状态到中文标签映射，未知值由调用组件自行兜底。
export const statusText: Record<string, string> = {
  completed: '已完成',
  complete: '已完成',
  running: '运行中',
  acting: '执行中',
  planning: '规划中',
  preparing_context: '准备上下文',
  verifying: '验收中',
  awaiting_approval: '等待审批',
  pending: '待处理',
  approved: '已批准',
  rejected: '已拒绝',
  failed: '失败',
  stopped: '已停止',
  queued: '排队中',
  blocked: '受阻',
  online: '在线',
  healthy: '正常',
  active: '活跃',
  idle: '空闲',
  default: '默认',
  todo: '待认领',
  in_progress: '进行中',
  review: '待验收',
}
