export const statusText: Record<string, string> = {
  completed: '已完成',
  complete: '已完成',
  running: '运行中',
  acting: '执行中',
  planning: '规划中',
  preparing_context: '准备上下文',
  awaiting_approval: '等待审批',
  pending: '待处理',
  approved: '已批准',
  rejected: '已拒绝',
  failed: '失败',
  stopped: '已停止',
  queued: '排队中',
  blocked: '受阻',
  online: '在线',
  healthy: '正常',
  active: '活跃',
  idle: '空闲',
  default: '默认',
  todo: '待认领',
  in_progress: '进行中',
  review: '待验收',
}
